--- 
title: "Visualize 120 Years of Summer Olympics"
author: "Chris Fang & Hongtao Hao"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
   bookdown::word_document2:
     toc: true
documentclass: article
github-repo: hongtaoh/olymvis-bookdown
description: "Olymvis"
---
# Preface{-}

```{r echo=FALSE}
library(bookdownplus)
```

This data visualization project was completed by Zihui (Chris) Fang and Hongtao Hao, with Equal Contribution, as the term paper for Professor Yong-Yeol Ahn's Data Visualization course in 2019 Fall.

This study analyzed the historical data which contains information on athletes in all the past modern Olympic Games. We tried to answer four questions:

1. How did female participation change over the years and how did these changes differ between continents?

2. Is there a home-field advantage at the Olympics?

3. How “efficient” is each participating country or region to get medals? and

4. Which sports had the highest number of participants?

Results showed that both total number of athletes and the rate of female participation have been increasing in the past 120 years. Also, there seems to exist a home-field advantage. Third, medal efficiency is highly correlated with participating country or region’s economic development. Finally, athletics, gymnastics, and swimming have the highest number of athletes.

The PDF version of our paper can be found [here](_book/olymvis-bookdown.pdf). You can access the [Word document](_book/olymvis-bookdown.docx) of this paper as well. 
